export const SYSTEM_LABELS_CUSTOMISATION = {
  SET_SYSTEM_LABELS_CUSTOMISATION:
    'SYSTEM_LABELS_CUSTOMISATION/SET_SYSTEM_LABELS_CUSTOMISATION',
};

export const setSystemLabelsCustomisations = (data: any) => ({
  type: SYSTEM_LABELS_CUSTOMISATION.SET_SYSTEM_LABELS_CUSTOMISATION,
  payload: data,
});
